/**
 * Script to embed the Ohm grammar into TypeScript for JSR compatibility
 */

const grammarPath = new URL("../src/dbml.ohm", import.meta.url);
const grammarContent = await Deno.readTextFile(grammarPath);

// Escape the grammar content for embedding in TypeScript
const escapedGrammar = grammarContent
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$/g, "\\$");

// Generate the embedded grammar module
const embeddedGrammarModule = `/**
 * Auto-generated file containing embedded Ohm grammar
 * Generated by scripts/embed-grammar.ts
 * DO NOT EDIT MANUALLY
 */

export const grammarSource = \`${escapedGrammar}\`;
`;

// Write the embedded grammar module
const outputPath = new URL("../src/grammar-embedded.ts", import.meta.url);
await Deno.writeTextFile(outputPath, embeddedGrammarModule);

console.log("✅ Grammar embedded successfully in src/grammar-embedded.ts");